gatewayConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 6211
  path: /api/g
  requestDelay: 500
  numThreads: 1

loggerConfig:
  outputDir: ./logs/
  outputFile: gateway.log

databaseConfig:
  dbConnections: 10
  dbUsername: cs122b_db134
  dbPassword: b~mzRzwNdWdE
  dbHostname: columbo-v5.ics.uci.edu
  dbPort: 3306
  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: cs122b_db134
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST

idmConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 6243
  path: /api/idm

idmEndpoints:
  EPUserRegister: /register
  EPUserLogin: /login
  EPSessionVerify: /session
  EPUserPrivilegeVerify: /privilege

moviesConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 6241
  path: /api/movies

moviesEndpoints:
  EPMovieSearch: /search
  EPMovieGet: /get/
  EPMovieAdd: /add
  EPMovieDelete: /delete/
  EPGenreGet: /genre
  EPGenreAdd: /add
  EPGenreMovie: /genre/
  EPStarSearch: /star/search
  EPStarGet: /star/
  EPStarAdd: /star/add
  EPStarIn: /star/starsin
  EPRating: /rating

billingConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 6543
  path: /api/billing

billingEndpoints:
  EPCartUpdate: /cart/update
  EPCartInsert: /cart/insert
  EPCartDelete: /cart/delete
  EPCartRetrieve: /cart/retrieve
  EPCartClear: /cart/clear
  EPCcInsert: /creditcard/insert
  EPCcUpdate: /creditcard/update
  EPCcDelete: /creditcard/delete
  EPCcRetrieve: /creditcard/retrieve
  EPCustomerInsert: /customer/insert
  EPCustomerUpdate: /customer/update
  EPCustomerRetrieve: /customer/retrieve
  EPOrderPlace: /order/place
  EPOrderRetrieve: /order/retrieve